In [1]:
# Cell 1 - Imports
import pandas as pd

In [4]:
import pandas as pd
import numpy as np

In [6]:
import pandas as pd

df = pd.read_csv("../data/processed/02_cleaned.csv")

In [7]:
df.head()

,timestamp,temperature,humidity,co2,yield_kg
0,2026-06-01 08:00:00,25.7,79.0,929.0,12.34
1,2026-06-01 09:00:00,24.8,83.0,945.0,12.55
2,2026-06-01 10:00:00,26.0,84.0,987.0,13.60
3,2026-06-01 11:00:00,27.3,82.0,984.0,13.49
4,2026-06-01 12:00:00,24.6,84.0,790.0,12.98


In [8]:
print(df.columns.tolist())

['timestamp', 'temperature', 'humidity', 'co2', 'yield_kg']


In [9]:
# Features (inputs)
X = df[['temperature', 'humidity', 'co2']]

# Target (output)
y = df['yield_kg']

In [10]:
print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   temperature  humidity    co2
0         25.7      79.0  929.0
1         24.8      83.0  945.0
2         26.0      84.0  987.0
3         27.3      82.0  984.0
4         24.6      84.0  790.0

Target:
0    12.34
1    12.55
2    13.60
3    13.49
4    12.98
Name: yield_kg, dtype: float64


In [11]:
df['temp_humidity'] = df['temperature'] * df['humidity']

In [12]:
df[['temperature', 'humidity', 'temp_humidity']].head()

,temperature,humidity,temp_humidity
0,25.7,79.0,2030.3
1,24.8,83.0,2058.4
2,26.0,84.0,2184.0
3,27.3,82.0,2238.6
4,24.6,84.0,2066.4


In [13]:
X = df[['temperature', 'humidity', 'co2', 'temp_humidity']]

In [14]:
print(X.head())

   temperature  humidity    co2  temp_humidity
0         25.7      79.0  929.0         2030.3
1         24.8      83.0  945.0         2058.4
2         26.0      84.0  987.0         2184.0
3         27.3      82.0  984.0         2238.6
4         24.6      84.0  790.0         2066.4


In [15]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

df = df.sort_values('timestamp')

df.head()

,timestamp,temperature,humidity,co2,yield_kg,temp_humidity
0,2026-06-01 08:00:00,25.7,79.0,929.0,12.34,2030.3
1,2026-06-01 09:00:00,24.8,83.0,945.0,12.55,2058.4
2,2026-06-01 10:00:00,26.0,84.0,987.0,13.60,2184.0
3,2026-06-01 11:00:00,27.3,82.0,984.0,13.49,2238.6
4,2026-06-01 12:00:00,24.6,84.0,790.0,12.98,2066.4


In [16]:
print(df['timestamp'].head())

0   2026-06-01 08:00:00
1   2026-06-01 09:00:00
2   2026-06-01 10:00:00
3   2026-06-01 11:00:00
4   2026-06-01 12:00:00
Name: timestamp, dtype: datetime64[us]


In [17]:
print(df['timestamp'].tail())

95   2026-06-05 07:00:00
96   2026-06-05 08:00:00
97   2026-06-05 09:00:00
98   2026-06-05 10:00:00
99   2026-06-05 11:00:00
Name: timestamp, dtype: datetime64[us]


In [18]:
print("First 5 timestamps:")
print(df['timestamp'].head())

print("\nLast 5 timestamps:")
print(df['timestamp'].tail())

First 5 timestamps:
0   2026-06-01 08:00:00
1   2026-06-01 09:00:00
2   2026-06-01 10:00:00
3   2026-06-01 11:00:00
4   2026-06-01 12:00:00
Name: timestamp, dtype: datetime64[us]

Last 5 timestamps:
95   2026-06-05 07:00:00
96   2026-06-05 08:00:00
97   2026-06-05 09:00:00
98   2026-06-05 10:00:00
99   2026-06-05 11:00:00
Name: timestamp, dtype: datetime64[us]


In [19]:
# Recreate X and y after sorting
X = df[['temperature', 'humidity', 'co2', 'temp_humidity']]
y = df['yield_kg']

# 80/20 chronological split
split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

In [20]:
print("Total Rows:", len(df))
print("Train Rows:", len(X_train))
print("Test Rows:", len(X_test))

Total Rows: 100
Train Rows: 80
Test Rows: 20


In [21]:
print("Train Start:", df.iloc[:split_index]['timestamp'].min())
print("Train End:", df.iloc[:split_index]['timestamp'].max())

print("\nTest Start:", df.iloc[split_index:]['timestamp'].min())
print("Test End:", df.iloc[split_index:]['timestamp'].max())

Train Start: 2026-06-01 08:00:00
Train End: 2026-06-04 15:00:00

Test Start: 2026-06-04 16:00:00
Test End: 2026-06-05 11:00:00


In [23]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
  Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
  Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\Sankeerthana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd

df = pd.read_csv("../data/processed/02_cleaned.csv")

In [3]:
df["timestamp"] = pd.to_datetime(df["timestamp"])
df = df.sort_values("timestamp")

In [4]:
df["temp_humidity"] = df["temperature"] * df["humidity"]

In [5]:
X = df[["temperature", "humidity", "co2", "temp_humidity"]]
y = df["yield_kg"]

In [6]:
split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(X_train_scaled[:5])

[[0.68656716 0.10526316 0.50793651 0.29928291]
 [0.55223881 0.31578947 0.5361552  0.33730212]
 [0.73134328 0.36842105 0.61022928 0.50723853]
 [0.92537313 0.26315789 0.60493827 0.58111216]
 [0.52238806 0.36842105 0.2627866  0.3481261 ]]


In [9]:
import pandas as pd

X_train_scaled_df = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)

X_test_scaled_df = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns
)

In [10]:
print(X_train_scaled_df.head())

   temperature  humidity       co2  temp_humidity
0     0.686567  0.105263  0.507937       0.299283
1     0.552239  0.315789  0.536155       0.337302
2     0.731343  0.368421  0.610229       0.507239
3     0.925373  0.263158  0.604938       0.581112
4     0.522388  0.368421  0.262787       0.348126


In [11]:
X_train_scaled_df.to_csv(
    "../data/processed/X_train.csv",
    index=False
)

X_test_scaled_df.to_csv(
    "../data/processed/X_test.csv",
    index=False
)

y_train.to_csv(
    "../data/processed/y_train.csv",
    index=False
)

y_test.to_csv(
    "../data/processed/y_test.csv",
    index=False
)

print("All files saved successfully!")

All files saved successfully!
